### PR TITLE
add japanese elmo pretrained model

### PR DESCRIPTION
**Pull request by enod**

### CODE REVIEW

**Comment by enod** [comment]
I have uploaded the weight and options file to Azure blob using my free trial account. As suggested [here](https://github.com/allenai/allennlp/issues/2025) could you please download the files and host it on your own service @schmmd ? Currently we are writing a paper that compares between ELMO, ULMFIt and BERT in japanese language and we will share the link once we finish.

**Comment by schmmd** [comment]
@enod thanks--I'll leave this issue open so we're sure to follow up if February passes and we still don't have your model in our gallery.

**Comment by enod** [comment]
@schmmd We ended up submitting our work to ACL. Until then, we can only share our pre-trained model with options file, similar to Portuguese language shown in https://allennlp.org/elmo.

**Comment by schmmd** [comment]
@enod it looks like this link is broken.  Is there a URL we should update it to?

**Comment by enod** [comment]
@schmmd 
I'm sorry for taking a while. Below are the links:
[options](https://exawizardsallenlp.blob.core.windows.net/data/options.json)  
[weights](https://exawizardsallenlp.blob.core.windows.net/data/weights.hdf5)
and [link](https://www.aclweb.org/anthology/P19-1458/) for the paper.

**Comment by schmmd** [comment]
Thanks!

**Pull request merged**
