### PR TITLE
Add new NER model.

### PR DESCRIPTION
**Pull request by schmmd**
This is blocked on https://github.com/allenai/allennlp/pull/1138.

Before merging, I need to verify the evaluation score and create a PR that updates the demo NER model.

### CODE REVIEW

**Comment by schmmd** [comment]
@matt-peters how is this verbiage?  Feel free to modify directly.

**Comment by schmmd** [comment]
I verified that the prediction command works on master.

**Comment by matt-peters** [comment]
How about:

```
This model is a reimplementation of the state-of-the-art NER model described in <a href = "https://arxiv.org/abs/1802.05365">Deep contextualized word representations</a>, and uses a biLSTM with CRF layer and ELMo embeddings.
It was trained on the <a href = "https://www.clips.uantwerpen.be/conll2003/ner/">CoNLL-2003</a> NER dataset, and has test set F1 of 92.5 for a single run, compared to the reported 92.22 +/- 0.10 F1 across five seeds in the reference paper.
```

**Comment by schmmd** [comment]
Done!

**Pull request merged**
