### PR TITLE
Add elmo page.

### PR DESCRIPTION
**Pull request by schmmd**

### CODE REVIEW

**Comment by matt-peters** [comment]
@schmmd -- Can you take a look?  The paper will contain a link to this page when it appears on Arxiv tomorrow so it'd be nice to have this merged by then.

**Comment by schmmd** [comment]
@matt-peters I made some minor edits.  Feel free to revert them if you don't like them.

If you ever need a pressing change to the website, feel free to merge without review.

**Comment by schmmd** [comment]
I'm the owner so I can't approve, but LGTM and merge any time ;-)

**Comment by matt-peters** [comment]
Saw the edits, thanks!  Once the paper appears on Arxiv tomorrow and I have a URL, I'll push another change to add a link back to the paper.

**Pull request merged**
