### PR TITLE
Upgrading site to use new AI2 logo and accent color

### PR DESCRIPTION
**Pull request by aaronsarnat**
## DON'T MERGE YET - this release needs to be coordinated with other logo rollout efforts

**In-browser screenshot:**
image

**Button Hover:**
image

### CODE REVIEW

**Comment by aaronsarnat** [comment]
@schmmd can you grant me admin access to this repo so I can assign you to review it and then merge when ready? :)

**Comment by schmmd** [comment]
@aaronsarnat I just gave ReViz "write" access which should be sufficient.

**Comment by aaronsarnat** [comment]
Great, thx!

**Comment by aaronsarnat** [comment]
Thanks @schmmd. I will review this in person w/ @Pelagic-sky tomorrow and then will merge when @carissas gives us the green light.

**Comment by aaronsarnat** [comment]
@Pelagic-sky PTAL at screenshots in description above. You can click images to zoom them

**Comment by Pelagic-sky** [comment]
LGTM

**Comment by aaronsarnat** [comment]
Merging on green

**Pull request merged**
